// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEN_6HUFibM4CdZexDTXCFiC7cNZNbgb8',
    appId: '1:529248480364:web:f86aa7347d8fcd4d34bc49',
    messagingSenderId: '529248480364',
    projectId: 'rezon-merch',
    authDomain: 'rezon-merch.firebaseapp.com',
    storageBucket: 'rezon-merch.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPMEV_9QW9RyFv8TBn2qj4LJl9s47Rw24',
    appId: '1:529248480364:android:d6cf7d520d1960ce34bc49',
    messagingSenderId: '529248480364',
    projectId: 'rezon-merch',
    storageBucket: 'rezon-merch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiXOyWRAEi8Pk3CUzxPHcqTW84NQIfxuw',
    appId: '1:529248480364:ios:0ebb541319b2343034bc49',
    messagingSenderId: '529248480364',
    projectId: 'rezon-merch',
    storageBucket: 'rezon-merch.firebasestorage.app',
    iosBundleId: 'com.example.agumerch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiXOyWRAEi8Pk3CUzxPHcqTW84NQIfxuw',
    appId: '1:529248480364:ios:0ebb541319b2343034bc49',
    messagingSenderId: '529248480364',
    projectId: 'rezon-merch',
    storageBucket: 'rezon-merch.firebasestorage.app',
    iosBundleId: 'com.example.agumerch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEN_6HUFibM4CdZexDTXCFiC7cNZNbgb8',
    appId: '1:529248480364:web:569870947f0b210e34bc49',
    messagingSenderId: '529248480364',
    projectId: 'rezon-merch',
    authDomain: 'rezon-merch.firebaseapp.com',
    storageBucket: 'rezon-merch.firebasestorage.app',
  );
}
